app:
  name: "VULSA"
  host: "0.0.0.0"
  port: 8000
  secret_key: "secret"
  debug: true

database:
  user: "user"
  password: "password"
  host: "pgbouncer"
  port: 6432
  name: "vulsa_db"

cache:
  host: "redis"
  port: 6379

kafka:
  host: "kafka"
  port: "9092"
  topics:
    link_clicked: "link_clicked"

clickhouse:
  user: "user"
  password: "password"
  host: "clickhouse"
  port: 8123
  name: "vulsa_ch"